/// CLASS WAS AUTOGENERATED  - DO NOT MODIFY

#pragma once
#include <sstream>
#include <string>

#include "common/message.h"
#include "common/quizzbot_types.h"

namespace quizzbot {
class JoinAckMessage : public MessageData {
public:
  JoinAckMessage() = default;

  // Default move because the types should be trivials..
  JoinAckMessage(JoinAckMessage &&other) noexcept = default;
  JoinAckMessage &operator=(JoinAckMessage &&other) = default;

  MessageType message_type() override { return MessageType::JOIN_ACK; }

  void unpack(std::string &ss) override { UNUSED(ss); }

  void pack(std::stringstream &ss) override { UNUSED(ss); }

  // Then Getters and setters

  // double dispatch to avoid casting.
  //  void dispatch(MessageHandler* handler) override {
  //  handler->handle(*this);
  //}

private:
};
}